name: 'Build Test .NET App'
description: 'I build, test, and upload artifacts for a .NET web app.  I am used as part of the Advanced GitHub Actions Talk'
inputs:
  dotnet-version:
    description: Version of .NET Core to use
    required: true
    default: 5.0.x
  solution:
    description: Solution path and solution file name
    required: true
   configuration:
     description: configuration parameter for dotnet
     required: true
     default: Release
   test-location:
     description: location of test files
     required: true
   cs-proj-file:
     description: cs proj file to created files for publishing
     required: true
   published-files:
     description: name of published files
     required: true
     default: myapp
runs:
  using: "composite"
  steps:
    
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    
    - name: Install dependencies
      run: dotnet restore "${{ inputs.solution }}"
    
    - name: Build
      run: dotnet build "${{ inputs.solution }}" --configuration ${{ inputs.configuration }} --no-restore
    
    - name: Test
      run: |
        dotnet test "${{ inputs.solution }}" --no-restore --verbosity normal  --logger "trx;LogFileName=test-results.trx"
        
    - name: Test Report
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: XUnit Tests            # Name of the check run which will be created
        path: "${{ inputs.test-location }}/*.trx"    # Path to test results
        reporter: dotnet-trx
      
    - name: Publish
      run: |
        dotnet publish "${{ inputs.cs-proj-file }}" -c ${{ inputs.configuration }} -o ${{ inputs. published-files }
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name:  ${{ inputs. published-files }
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ inputs. published-files }/**
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 90
